// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHNUS1lBItEgLsPQKe3i2QnugQDuqSfHE',
    appId: '1:155591398601:web:8445a1c530039af1df6918',
    messagingSenderId: '155591398601',
    projectId: 'reps-53098',
    authDomain: 'reps-53098.firebaseapp.com',
    storageBucket: 'reps-53098.firebasestorage.app',
    measurementId: 'G-XHFK8LVRJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEw5TrgIkfMy6J_YsynK-AUxivO47JpZM',
    appId: '1:155591398601:android:0a4d14bb2fefb9addf6918',
    messagingSenderId: '155591398601',
    projectId: 'reps-53098',
    storageBucket: 'reps-53098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbicaXCk4wQqWIBjrixd-krKzUPR7BB5w',
    appId: '1:155591398601:ios:3834c75dde80924edf6918',
    messagingSenderId: '155591398601',
    projectId: 'reps-53098',
    storageBucket: 'reps-53098.firebasestorage.app',
    iosBundleId: 'com.example.repsTrainerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbicaXCk4wQqWIBjrixd-krKzUPR7BB5w',
    appId: '1:155591398601:ios:3834c75dde80924edf6918',
    messagingSenderId: '155591398601',
    projectId: 'reps-53098',
    storageBucket: 'reps-53098.firebasestorage.app',
    iosBundleId: 'com.example.repsTrainerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHNUS1lBItEgLsPQKe3i2QnugQDuqSfHE',
    appId: '1:155591398601:web:0618c7d9ea454ac2df6918',
    messagingSenderId: '155591398601',
    projectId: 'reps-53098',
    authDomain: 'reps-53098.firebaseapp.com',
    storageBucket: 'reps-53098.firebasestorage.app',
    measurementId: 'G-ZE97393H3T',
  );

}